[build]
  publish = "."
  command = "echo 'No build process required for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect rules for clean URLs
[[redirects]]
  from = "/create-token"
  to = "/create-token/index.html"
  status = 200

[[redirects]]
  from = "/my-portfolio"
  to = "/my-portfolio/index.html"  
  status = 200

# Security redirects
[[redirects]]
  from = "https://lunalaunch.netlify.app/*"
  to = "https://your-custom-domain.com/:splat"
  status = 301
  force = false

[dev]
  command = "python -m http.server 8888"
  port = 8888
  publish = "."